[package]
name = "chant"
version = "0.1.0"
edition = "2024"

[dependencies]
trove = { git = "https://github.com/mentalblood0/trove" }
wool = { git = "https://github.com/mentalblood0/wool" }
anyhow = { version = "1.0", features = ["std", "backtrace"] }
fallible-iterator = { version = "0.3", features = ["std"] }
frankenstein = { version = "0.47", features = ["client-ureq"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["std", "unbounded_depth"] }
serde-saphyr = { git = "https://github.com/bourumir-wyngs/serde-saphyr" }
regex = "1.12.3"

[dev-dependencies]
nanorand = "0.8"
pretty_assertions = "1.4"
